# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jayvaghani
# "service" is the name of this project. This will also be added to your AWS resource names.
service: kpgu-serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 512

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-dotenv-plugin
